### PR TITLE
A Exception Customisation

### LINKED ISSUE #137: [PE-D] Suggestion for tutorial circuit
I think the 'set r/l/c/v VALUE' instruction is a bit ambiguous, that why I enter the exactly same line at the first time. Maybe you can make it clearer?

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ZhongNingmou/ped#3

### LINKED ISSUE #142: [PE-D] Tutorial not interactive enough
The tutorial does not really care what did I set. Even I did not follow the instruction, it still goes on without make me aware of what I did wrong. But fortunately, if I do not set r, then the tutorial will stuck there. So seems it's just a UI issue.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Lee-Juntong/ped#3

### LINKED ISSUE #143: [PE-D] Instruction not customised for different tutorials
For adding component, the example provided is `add parallel c 500`, however, for tutorial circuit, template r, seems we are not allowed to add a capacitor

-------------
Labels: `severity.High` `type.DocumentationBug`
original: Lee-Juntong/ped#4

### LINKED ISSUE #144: [PE-D] Invalid instruction
If I follow the tutorial, set v and r, then it still asks me to set another value. Seems the app does not consider the case people trys this tutorial.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Lee-Juntong/ped#5

### LINKED ISSUE #147: [PE-D] Exception  not customised
Generally, most commands simply fall to invalid command without give better explanation.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Lee-Juntong/ped#8

### PR DESCRIPTION
**Pull request by sevenseasofbri**
For `model`

Yo I'm adding UI fixes to this

closes #137 
closes #142 
closes #143 
closes #144
closes #147 

And part of #155

### CODE REVIEW

File: src/main/java/seedu/duke/model/gates/NandGate.java [hunk 1]
```diff
@@ -9,9 +9,10 @@
      * Performs bitwise NAND (~&) operation on the input instance variables.
```
Comment (hughjazzman) [inline src/main/java/seedu/duke/model/gates/NandGate.java:9]: These JavaDoc could be improved, since the `boolean` is returned also.

File: src/main/java/seedu/duke/model/exceptions/templateexceptions/InvalidComponentException.java [hunk 2]
```diff
@@ -0,0 +1,9 @@
+package seedu.duke.model.exceptions.templateexceptions;
+
+public class InvalidComponentException extends TemplateException {
+    public InvalidComponentException(String s) {
+        super("You've tried to set a " + s + " in a circuit template that doesn't support " + s + ".\nIf you want to "
+                + "use " + s + " in your circuit, then consider trying out " + (s.equals("l") ? "lc or rl" :
```
Comment (hughjazzman) [inline src/main/java/seedu/duke/model/exceptions/templateexceptions/InvalidComponentException.java]: Maybe say something like '`template lc`' or '`template rl`'?

**Review by hughjazzman — COMMENTED** [review]
Looks good, maybe can try test more of the exceptions in text-ui-test?

File: src/main/java/seedu/duke/model/gates/NandGate.java (hunk 1 above)
Comment (sevenseasofbri) [reply src/main/java/seedu/duke/model/gates/NandGate.java:9]: oh! thanks for pointing out

File: src/main/java/seedu/duke/model/exceptions/templateexceptions/InvalidComponentException.java (hunk 2 above)
Comment (sevenseasofbri) [reply src/main/java/seedu/duke/model/exceptions/templateexceptions/InvalidComponentException.java]: ah okay

File: src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java [hunk 3]
```diff
@@ -11,7 +11,8 @@
 
 public class TutorialCircuitCommand extends SummaryCommand implements TutorialCommand {
     private final Parser parser = new Parser();
-    private static final String[] orderOfInstructions = {"template", "set v", "set", "set", "add", "calc"};
+    private static final String[] orderOfInstructions = {"template rc", "set v", "set r", "set c", "add parallel c",
```
Comment (hughjazzman) [inline src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java:14]: Yup try maybe add wrong commands not matching these in input.txt to see what happens.

Comment (sevenseasofbri) [reply src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java:14]: Okie cool

**Review by hughjazzman — APPROVED** [review]
LGTM!
