### PR TITLE
Issue #88, Update HelpCircuitCommand

### LINKED ISSUE #88: Update HelpCircuitCommand
Update `HelpCircuitCommand`
* Rename to `TutorialCircuitCommand`.
* Update formatting to look cleaner, with proper newlines.
* Add `SummaryCommand` at the end.
* Track number of incorrect attempts (`priority.Low`)

`CircuitCommand` should also be updated to print Voltage along with template.

### PR DESCRIPTION
**Pull request by dorianfong98**

### CODE REVIEW

File: src/main/java/seedu/duke/ui/Ui.java [hunk 1]
```diff
@@ -32,7 +32,7 @@
         "Great! Say, do you think we could find effective power/current consumed by the circuit?"
             + "Or even effective resistance/inductance/capacitance? Yes!\n"
             + "Lets try it out. Type 'calc' followed by 'ceff'/'leff'/'reff'/'power'/'current' and enter. :D",
-        "Great! You're set to use\n" + "CLIrcuit Assistant" + "Enjoy! :)\n type 'exit' to exit this mode.\n"};
+        "Great! You're set to use\n" + "CLIrcuit Assistant" + " Enjoy! :)\n type 'exit' to exit this mode.\n"};
```
Comment (hughjazzman) [inline src/main/java/seedu/duke/ui/Ui.java]: Any reason why this doesn't use the CLIrcuit Assistant logo? And Enjoy being on the same line? Consider using EXPECTED.txt and ACTUAL.txt, which you'll have to update, to check the formatting.

Comment (sevenseasofbri) [reply src/main/java/seedu/duke/ui/Ui.java]: The CLIrcuit Assistant thing, I had removed the logo because of runtest. However, forgot to put it back..

File: src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java [hunk 2]
```diff
@@ -8,6 +8,16 @@
...
+    private static final String COMMAND_SUMMARY = "Here's a summary of available commands: \n"
+            + "+-----------+----------------------------+--------------------+\n"
+            + "|  Action   |           Format           |      Examples      |\n"
+            + "+-----------+----------------------------+--------------------+\n"
+            + "| Tutorial  | tutorial MODE              | tutorial boolean   |\n"
+            + "| Template  | template TEMPLATE          | template rc        |\n"
+            + "| Set       | set COMPONENT VALUE        | set r 500          |\n"
+            + "| Add       | add CONFIG COMPONENT VALUE | add parallel c 500 |\n"
+            + "| Calculate | calc EFF_VALUE             | calc ceff          |\n"
+            + "+-----------+----------------------------+--------------------+\n";
```
Comment (sevenseasofbri) [inline src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java]: Err I'm not sure but why is this summary table in TutorialCircuitCommand?
Can use the summary table from SummaryCommand, perhaps create an object of SummaryCommand and print it?

File: src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java [hunk 3]
```diff
@@ -54,10 +64,14 @@ public boolean continueTutorial(String command, Ui ui) throws DukeException {
         if (command.equals("exit")) {
             return false;
         }
-        
+        if (numOfCommandsDone >= 8 || !command.matches(orderOfInstructions[numOfCommandsDone] + "(.*)")) {
+            throw new DukeException("Please revise! Or you'll struggle with the module!\n" + "You got this! ᕦ(ò_óˇ)ᕤ\n"
+                    + "To exit Tutorial Mode, simply type 'exit' and press Enter.");
+        }
```
Comment (sevenseasofbri) [inline src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java]: Wait.. this will print once the person goes through 8 commands, and then print again because 8  > 6 commands done

**Comment by sevenseasofbri** [comment]
Also you gotta update expected and unix expected files so that the runtests pass

File: src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java (hunk 3 above)
Comment (hughjazzman) [reply src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java]: Adding on to this, how come there are two sets of `DukeException` being thrown?

File: src/main/java/seedu/duke/model/template/LcTemplate.java [hunk 4]
```diff
@@ -100,7 +100,8 @@ public void setComponent(String s, double value) {
      */
     @Override
     public String toString() {
-        return LC_TEMPLATE + "Total Capacitance: " + capacitor + System.lineSeparator()
+        return "Current Voltage: " + initialPowerSupply + System.lineSeparator()
+                + LC_TEMPLATE + "Total Capacitance: " + capacitor + System.lineSeparator()
```
Comment (sevenseasofbri) [inline src/main/java/seedu/duke/model/template/LcTemplate.java]: Perhaps could have added Current Voltage printed after the template?

Comment (hughjazzman) [reply src/main/java/seedu/duke/model/template/LcTemplate.java]: Consider putting this in `CircuitTemplate` instead? Then subclasses can just call `super.toString()`.

File: src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java [hunk 5]
```diff
@@ -1,21 +1,25 @@
...
 import java.util.logging.Level;
 
-public class TutorialCircuitCommand extends CircuitCommand implements TutorialCommand {
+public class TutorialCircuitCommand extends SummaryCommand implements TutorialCommand {
+
     private static final Parser PARSER = new Parser();
     private static final String[] orderOfInstructions = {"template", "set v", "set", "set", "add", "calc"};
     private int numOfCommandsDone = 0;
     private final Ui ui;
+    protected SummaryCommand summary;
```
Comment (sevenseasofbri) [inline src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java]: I don't think we need to instantiate anymore since we are inheriting SummaryCommand here

File: src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java [hunk 6]
```diff
@@ -1,21 +1,25 @@
...
 
     public TutorialCircuitCommand() {
         super();
         ui = new Ui(); // Create its own Ui instance, can be a Ui subclass later on
+        summary = new SummaryCommand();
```
Comment (sevenseasofbri) [inline src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java]: Can remove this also

File: src/main/java/seedu/duke/logic/commands/SummaryCommand.java [hunk 7]
```diff
@@ -6,7 +6,8 @@
             + "+-----------+----------------------------+--------------------+\n"
             + "|  Action   |           Format           |      Examples      |\n"
```
Comment (hughjazzman) [inline src/main/java/seedu/duke/logic/commands/SummaryCommand.java]: Will be updated by @oasisbeatle

File: src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java (hunk 5 above)
Comment (hughjazzman) [reply src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java]: 👍 
```suggestion
```

File: src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java (hunk 6 above)
Comment (hughjazzman) [reply src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java]:
```suggestion
```

**Review by hughjazzman — COMMENTED** [review]
Final changes before approval.

File: text-ui-test/EXPECTED.TXT [hunk 8]
```diff
@@ -45,16 +48,34 @@ Nice, added a 40.0 µF
...
++-----------+----------------------------+--------------------+
+|  Action   |           Format           |      Examples      |
++-----------+----------------------------+--------------------+
+| Summary   | summary                    | summary            |
+| Tutorial  | tutorial MODE              | tutorial boolean   |
+| Template  | template TEMPLATE          | template rc        |
+| Set       | set COMPONENT VALUE        | set r 500          |
+| Add       | add CONFIG COMPONENT VALUE | add parallel c 500 |
+| Calculate | calc EFF_VALUE             | calc ceff          |
++-----------+----------------------------+--------------------+
```
Comment (hughjazzman) [inline text-ui-test/EXPECTED.TXT]:
```suggestion
+-----------+----------------------------+---------------------+
|  Command  |         Circuit            |      Boolean        |
+-----------+----------------------------+---------------------+
| Tutorial  | tutorial circuit           | tutorial boolean    |
| Template  | template TEMPLATE          | template TEMPLATE   |
| Summary   | summary                    | summary             |
| Set       | set COMPONENT VALUE        | set INPUT BOOLVALUE |
| Add       | add CONFIG COMPONENT VALUE | add INPUT GATE      |
| Calculate | calc EFF_VALUE             | calc                |
| Exit      | exit                       | exit                |
| Print     | print                      | print               |
+-----------+----------------------------+---------------------+

Here's a summary of the command parameters: 
+-----------+----------------------------------+-------------------------------+
| Parameter |       Circuit Params             | Boolean Params                |
+-----------+----------------------------------+-------------------------------+
| TEMPLATE  | rc, rl, r, cl                    | boolean                       |
| COMPONENT | r, c, l, v                       | N.A.                          |
| CONFIG    | parallel, series                 | N.A                           |
| EFF_VALUE | reff, ceff, leff, current, power | N.A                           |
| VALUE     | any number of double datatype    | N.A                           |
| INPUT     | N.A                              | A, B, C, D, E, F, G           |
| GATE      | N.A                              | or, and, nor, nand, xor, xnor |
| BOOLVALUE | N.A                              | 0, 1                          |
+-----------+----------------------------------+-------------------------------+
```

File: text-ui-test/EXPECTED.TXT [hunk 9]
```diff
@@ -45,16 +48,49 @@ Nice, added a 40.0 µF
...
-CLIrcuit AssistantEnjoy! :)
+ _____ _      _____                _ _                      _     _              _
+/ ____| |    |_   _|              (_) |       /\           (_)   | |            | |
+| |    | |      | |  _ __ ___ _   _ _| |_     /  \   ___ ___ _ ___| |_ __ _ _ __ | |_
+| |    | |      | | | '__/ __| | | | | __|   / /\ \ / __/ __| / __| __/ _` | '_ \| __|
+| |____| |____ _| |_| | | (__| |_| | | |_   / ____ \\__ \__ \ \__ \ || (_| | | | | |_
+\_____|______|_____|_|  \___|\__,_|_|\__| /_/    \_\___/___/_|___/\__\__,_|_| |_|\__|Enjoy! :)
  type 'exit' to exit this mode.
 
+You have exited Tutorial Mode!
```
Comment (hughjazzman) [inline text-ui-test/EXPECTED.TXT:67]:
```suggestion
You have exited Tutorial Mode!
Here's a summary of available commands:
```

**Review by hughjazzman — APPROVED** [review]
LGTM
